<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SixLabors.PolygonClipper</AssemblyName>
    <AssemblyTitle>SixLabors.PolygonClipper</AssemblyTitle>
    <RootNamespace>SixLabors.PolygonClipper</RootNamespace>
    <PackageId>SixLabors.PolygonClipper</PackageId>
    <PackageIcon>sixlabors.polygonclipper.128.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl Condition="'$(RepositoryUrl)' == ''">https://github.com/SixLabors/PolygonClipper/</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageTags></PackageTags>
    <Description></Description>
    <Configurations>Debug;Release</Configurations>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <CodeAnalysisRuleSet>..\sixlabors.ruleset</CodeAnalysisRuleSet>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <!--Bump to v1.0 prior to tagged release.-->
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
  </PropertyGroup>

  <Choose>
    <When Condition="$(SIXLABORS_TESTING_PREVIEW) == true">
      <PropertyGroup>
        <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\shared-infrastructure\branding\icons\polygonclipper\sixlabors.polygonclipper.128.png" Pack="true" PackagePath="" />
    <None Include="..\..\SixLabors.PolygonClipper.props" Pack="true" PackagePath="build" />
  </ItemGroup>

  <Import Project="..\..\shared-infrastructure\src\SharedInfrastructure\SharedInfrastructure.projitems" Label="Shared" />

</Project>
