<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--Used to hide test project from dotnet test-->
        <IsTestProject>false</IsTestProject>
        <!-- Is disabled to avoid conflicts with the shared infrastructure -->
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

  <Choose>
    <When Condition="$(SIXLABORS_TESTING_PREVIEW) == true">
      <PropertyGroup>
        <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
      </PropertyGroup>
    </Otherwise>
  </Choose>

</Project>
